### ISSUE TITLE
Which paper

### ISSUE THREAD

**Issue by yiboin** [zhreshold/PersonReIdentification#1]
This code is so cool, but I still have some questions to fully understand it. Could you tell me the paper's name for this code? Thank you !

**Comment by zhreshold** [comment]
It's just experimental stuff, not yet posted to any paper.

**Comment by yiboin** [comment]
Could you tell me how to get the ranksvm64? I mean the source code of ranksvm64.

**Comment by zhreshold** [comment]
https://www.csie.ntu.edu.tw/~cjlin/libsvm/
